// Generated by CoffeeScript 1.6.2
describe("Model :: AccountModel", function() {
  var account;

  account = {
    token: false
  };
  beforeEach(function() {
    var done, that;

    that = this;
    done = false;
    require(['models/AccountModel'], function(Model) {
      that.model = new Model();
      that.done = true;
    });
    waitsFor(function() {
      return done;
    }, "Create Models");
  });
  return it("should be defined", function() {
    return expect(this.model).toBeDefined();
  });
});
