// Generated by CoffeeScript 1.6.2
describe("App namespace", function() {
  return it("should be defined", function() {
    return require(['app'], function(App) {
      return expect(App).toBeDefined();
    });
  });
});

describe("first test", function() {
  return it("is true", function() {
    expect(true).toBeTruthy(false);
  });
});

describe("first test2", function() {
  return it("is true", function() {
    expect(true).toBeTruthy();
  });
});
