// Generated by CoffeeScript 1.6.2
require.config({
  baseUrl: "../../js/",
  urlArgs: 'cb=' + Math.random(),
  paths: {
    jquery: 'libs/jquery.min',
    backbone: '../../scripts/vendor/backbone-amd/backbone-min',
    underscore: '../../scripts/vendor/underscore-amd/underscore-min',
    marionette: '../../scripts/vendor/backbone.marionette/lib/core/amd/backbone.marionette.min',
    'backbone.wreqr': '../../scripts/vendor/backbone.wreqr/lib/amd/backbone.wreqr.min',
    'backbone.eventbinder': '../../scripts/vendor/backbone.eventbinder/lib/amd/backbone.eventbinder',
    'backbone.babysitter': '../../scripts/vendor/backbone.babysitter/lib/amd/backbone.babysitter.min',
    bootstrap: 'libs/bootstrap.min',
    modernizr: 'libs/modernizr.min',
    jasmine: '../../scripts/vendor/jasmine/lib/jasmine-core/jasmine',
    'jasmine-html': '../../scripts/vendor/jasmine/lib/jasmine-core/jasmine-html',
    spec: '../test/jasmine/spec'
  },
  shim: {
    underscore: {
      exports: "_"
    },
    backbone: {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    jasmine: {
      exports: 'jasmine'
    },
    'jasmine-html': {
      deps: ['jasmine'],
      exports: 'jasmine'
    }
  }
});

window.store = "TestStore";

require(['underscore', 'jquery', 'jasmine-html'], function(_, $, jasmine) {
  var htmlReporter, jasmineEnv, specs;

  jasmineEnv = jasmine.getEnv();
  jasmineEnv.updateInterval = 1000;
  htmlReporter = new jasmine.HtmlReporter();
  jasmineEnv.addReporter(htmlReporter);
  jasmineEnv.specFilter = function(spec) {
    return htmlReporter.specFilter(spec);
  };
  specs = [];
  specs.push('./spec/app_spec');
  return $(function() {
    return require(specs, function() {
      return jasmineEnv.execute();
    });
  });
});
