// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["backbone", "marionette"], function(Backbone, Marionette) {
  var API, Router, _ref;

  Router = (function(_super) {
    __extends(Router, _super);

    function Router() {
      _ref = Router.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Router.prototype.appRoutes = {
      "about": "about"
    };

    return Router;

  })(Backbone.Marionette.AppRouter);
  API = {
    about: function(state, tate) {
      console.log("-About ", tate);
      Controller.show();
    },
    aboutme: function() {
      console.log("About me");
      Controller.showAboutMe();
      Backbone.history.navigate("about", {
        trigger: false,
        replace: true
      });
    }
  };
  return Router;
});
