// Generated by CoffeeScript 1.6.2
define(["underscore", "marionette", "text!./../templates/account_layout.html"], function(_, Marionette, tmltMainLayout) {
  var LayoutView;

  LayoutView = Marionette.Layout.extend({
    template: _.template(tmltMainLayout)
  });
  return new LayoutView;
});
