// Generated by CoffeeScript 1.6.2
define(["backbone", "marionette", "msgmngr", "models/Account"], function(Backbone, Marionette, msgMngr) {
  var app;

  console.log("App load");
  app = new Marionette.Application();
  app.addRegions({
    content: "#content",
    navpanel: "#navpanel",
    footer: '#footer'
  });
  app.on("initialize:before", function() {
    console.log("initialize:before");
  });
  app.on("initialize:after", function() {
    console.log("initialize:after");
    Backbone.history.start();
  });
  app.addInitializer(function(options) {
    return console.log("initialize app");
  });
  return app;
});
