// Generated by CoffeeScript 1.6.2
define(["backbone", "marionette", "modules/account/views/AccountLayoutsView"], function(Backbone, Marionette, AccountModule) {
  var App;

  console.log("App load");
  App = new Marionette.Application();
  App.addRegions({
    mainRegion: "#container"
  });
  App.on("initialize:before", function() {
    App.mainRegion.show(AccountModule);
    console.log("initialize:before");
  });
  App.on("initialize:after", function() {
    console.log("initialize:after");
    Backbone.history.start();
  });
  return App;
});
