// Generated by CoffeeScript 1.6.2
define(["backbone.wreqr"], function(Wreqr) {
  return {
    reqres: new Wreqr.RequestResponse(),
    commands: new Wreqr.Commands(),
    events: new Wreqr.EventAggregator()
  };
});
