// Generated by CoffeeScript 1.6.2
define(["backbone", "marionette"], function(Backbone, Marionette) {
  var Model;

  return Model = Backbone.Model.extend({
    initialize: function() {
      console.log("AccountModel initialize");
    }
  });
});
